### PR TITLE
Fixed image links and modified other minor stuff

### PR DESCRIPTION
**Pull request by sayakpaul**
It is already in pretty brilliant shape. I did the following:
- Moved all the images to a directory central to the particular folder `Fundamentals`.
- Modified very minor stuff. 

Let me know your thoughts.

### CODE REVIEW

**Comment by aabedraba** [comment]
Adding my 2 cents. 

Probably worth adding an images section to all folders, so the structure is similar. 

Also, is there a systematic way to attribute copyright ownership if needed? Does it even make sense to have one?

**Comment by sayakpaul** [comment]
Yeah, that would need to be taken care of by the respective members. As for the copyrights, @imransalam will add all the citations afterward as far as I know.

**Comment by imransalam** [comment]
> Yeah, that would need to be taken care of by the respective members. As for the copyrights, @imransalam will add all the citations afterward as far as I know.

Yes. I will add the citations

**Review by imransalam — APPROVED** [review]
Looks great. Thanks for the help Sayak!

**Review by almo — APPROVED** [review]
Great!
Thank you all!

**Pull request merged**
